# Generated by Django 2.2.5 on 2020-04-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowToUseFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('how_to_trim', models.TextField(max_length=10000, null=True)),
                ('how_to_store', models.TextField(max_length=10000, null=True)),
            ],
        ),
    ]
