# Generated by Django 2.2.5 on 2020-05-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
