# Generated by Django 2.2.5 on 2020-05-16 04:40

from django.db import migrations, models
import foods.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtousefood',
            name='name',
            field=models.CharField(max_length=100, validators=[foods.my_validator.my_validator]),
        ),
    ]
