# Generated by Django 2.2.5 on 2020-05-16 04:44

from django.db import migrations, models
import foods.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20200516_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=20, validators=[foods.my_validator.my_validator]),
        ),
        migrations.AlterField(
            model_name='howtousefood',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
