# Generated by Django 2.2.5 on 2020-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_auto_20200516_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(error_messages={'required': '양수를 입력해주세요'}, null=True),
        ),
    ]
