# Generated by Django 2.2.5 on 2020-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20200516_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
