# Generated by Django 2.2.5 on 2020-05-16 09:03

from django.db import migrations, models
import foods.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_auto_20200516_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.PositiveIntegerField(null=True, validators=[foods.my_validator.validate_quantity]),
        ),
    ]
