# Generated by Django 3.0.7 on 2020-06-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(default='default.png', upload_to='recipies')),
                ('how_to_create', models.TextField(max_length=10000, null=True)),
                ('subname', models.CharField(max_length=100, null=True)),
                ('recipe_quantity', models.CharField(max_length=100, null=True)),
                ('recipe_time', models.CharField(max_length=100, null=True)),
                ('recipe_level', models.CharField(max_length=100, null=True)),
                ('food', models.ManyToManyField(blank=True, related_name='recipies', to='recipies.FoodInRecipe')),
            ],
        ),
    ]
