# Generated by Django 3.0.7 on 2020-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
