# Generated by Django 3.0.7 on 2020-06-09 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_auto_20200609_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
        migrations.DeleteModel(
            name='FoodLink',
        ),
    ]
