# Generated by Django 3.0.7 on 2020-06-09 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipies', '0005_recipelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePercent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percents', to='recipies.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
