# Generated by Django 3.0.7 on 2020-06-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0006_recipepercent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipePercent',
        ),
    ]
