# Generated by Django 3.0.7 on 2020-06-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0008_recipepercent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='percent',
        ),
    ]
