# Generated by Django 3.0.7 on 2020-06-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0009_remove_recipe_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_level',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_time',
        ),
    ]
