# Generated by Django 3.0.7 on 2020-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0011_auto_20200609_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
