# Generated by Django 3.0.7 on 2020-06-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0012_recipe_recipe_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='subname',
        ),
    ]
