# Generated by Django 3.0.7 on 2020-06-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0013_auto_20200610_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinrecipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='recipies.Recipe'),
        ),
    ]
